workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never  # Prevent pipeline run for push event
    - when: always # Run pipeline for all other cases

default:
  image: 'ruby:2.7'
  before_script:
  - echo "Deploying microservices"
  - echo $CI_COMMIT_BRANCH

stages:
  - build
  - deploy

build:
  tags:
  - runnertag
  stage: build
  script:
    - if [[ $npm_install == "no" ]]; then echo "Skipping npm install"; else npm install; fi
  artifacts:
    paths:
      - node_modules
  only:
  - master

deploy:
  tags:
  - runnertag
  stage: deploy
  script:
    - export INSTANCE_IPS=$(aws autoscaling describe-auto-scaling-instances --region region-name --output text --query "AutoScalingInstances[?AutoScalingGroupName=='group-name'].InstanceId" | xargs -n1 aws ec2 describe-instances --instance-ids $ID --region region-name --query "Reservations[].Instances[].PrivateIpAddress" --output text)
    - INSTANCE_COUNT=0
    - for IP in $INSTANCE_IPS; do
        ((INSTANCE_COUNT++))
        scp -r node_modules/ ubuntu@$IP:~/path/to/folder;
        if [ $INSTANCE_COUNT -eq 1 ] && [ "$migration" == "yes" ]; then
            ssh ubuntu@$IP 'cd path/to/folder;git checkout $BRANCH_NAME;git pull;npm run migrate;sleep 10;pm2 restart 2;sleep 60;pm2 log 2 --lines 1000 --nostream;sleep 60;pm2 restart 3 4;sleep 20;pm2 restart 5 6;sleep 20;pm2 restart 7 8 9;';
        else
            ssh ubuntu@$IP 'cd path/to/folder;git checkout $BRANCH_NAME;git pull;pm2 restart 2;sleep 60;pm2 log 2 --lines 1000 --nostream;sleep 60;pm2 restart 3 4;sleep 20;pm2 restart 5 6;sleep 20;pm2 restart 7 8 9;';
        fi
    done
  only:
    - master